apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/orikerbis/application-repo.git"
      targetRevision: develop
      path: employee-app
      helm:
        valueFiles:
          - $values/environments/dev/values.yaml
    - repoURL: "https://github.com/orikerbis/git-ops-repo.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: employee-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true