global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: f638d9956116414a64f26c6d78146b2d031c4a30
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: f638d9956116414a64f26c6d78146b2d031c4a30
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
