global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: 84c356e4100f49d3364013b80c04df1371c1ef1a
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: 84c356e4100f49d3364013b80c04df1371c1ef1a
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
