global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: 1410ec793d3afdf9b93813004640e7ec114954be
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: 1410ec793d3afdf9b93813004640e7ec114954be
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
