global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: c5884ea9978bc8d24290a66bbfb02b2bf81fe3a2
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: c5884ea9978bc8d24290a66bbfb02b2bf81fe3a2
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
