global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: 1384f6d42ad5d5cbdd3bd4ddeb9d6b77320baf65
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: 1384f6d42ad5d5cbdd3bd4ddeb9d6b77320baf65
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
