global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: 0214731982611e38d0c53d8181e986f45a5ae8ad
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: 0214731982611e38d0c53d8181e986f45a5ae8ad
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
