global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: 983ecbcdab1a271f7827f78c6c5990cce8f67bec
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: 983ecbcdab1a271f7827f78c6c5990cce8f67bec
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
