global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
  secretName: "app/dev/db-credentials"
grafana:
  service:
    name: prometheus-grafana
    port: 80
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: "da68b999d627e48ff0a23396f529ff21655be038"
  service:
    name: "dev-employee-app-frontend"
    type: NodePort
    port: 80
  replicaCount: 3
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: "da68b999d627e48ff0a23396f529ff21655be038"
  service:
    name: "dev-employee-app-backend"
    type: NodePort
    port: 3001
  replicaCount: 2
