global:
  imagePullPolicy: IfNotPresent
  namespace: employee-app
client:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/frontend
    tag: e1434f50f6b969066c34d5bc80e8c41d12969ec0
  service:
    name: employee-app-frontend
    type: ClusterIP
    port: 80
  replicaCount: 1
server:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/backend
    tag: e1434f50f6b969066c34d5bc80e8c41d12969ec0
  service:
    name: employee-app-backend
    type: ClusterIP
    port: 3001
  replicaCount: 1
